
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/layout/Sidebar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ConfigProvider } from "antd";
import HeaderDashborad from "@/components/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// const queryClient = new QueryClient();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      // dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* <QueryClientProvider client={queryClient}> */}
          <ConfigProvider
            direction="rtl"
            theme={{
              token: {
                fontFamily: `${geistSans.style.fontFamily}, sans-serif`,
              },
            }}>
            <div className="flex h-screen">
              <div className="flex-1 flex flex-col overflow-hidden">
                <HeaderDashborad />
                <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200 p-4 md:p-6">
                  {children}
                </main>
              </div>
              <Sidebar />
            </div>
          </ConfigProvider>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
