import type { Metadata } from "next";
import faIR from "antd/locale/fa_IR";
import "../styles/globals.css";
import Sidebar from "@/components/admin/layout/Sidebar";
import { ConfigProvider } from "antd";
import HeaderDashborad from "@/components/admin/layout/Header";
import localFont from "next/font/local";
import Providers from "./providers";
import { ToastContainer } from "react-toastify";

const iranYekan = localFont({
  src: [
    {
      path: "../public/fonts/iranyekanwebregular.b95439c1.b95439c1.woff",
      weight: "400",
    },
    {
      path: "../public/fonts/iranyekanwebmedium.2d4f96e5.2d4f96e5.woff",
      weight: "500",
    },
    {
      path: "../public/fonts/iranyekanwebbold.e298fdc6.e298fdc6.woff",
      weight: "700",
    },
    {
      path: "../public/fonts/iranyekanwebextrabold.9346e9a2.9346e9a2.woff",
      weight: "800",
    },
  ],
  variable: "--font-iranyekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ReactNode } from "react";

export default function RootLayout({ children }: LayoutProp) {
  return (
    <html lang="fa" className={`${iranYekan.variable} h-full antialiased`}>
      <body className="w-full min-h-full">
        <Providers>
          <ConfigProvider
            direction="rtl"
            locale={faIR}
            theme={{
              token: {
                fontFamily: "var(--font-iranyekan), sans-serif",
              },
            }}
          >
            {children}
          </ConfigProvider>

          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
