export const categories = [
  { id: 19, label: "HTML & CSS" },
  { id: 1, label: "ارتقای مهارت ها" },
  { id: 2, label: "امنیت" },
  { id: 21, label: "برنامه نویسی" },
  { id: 3, label: "بک اند" },
  { id: 4, label: "پایتون" },
  { id: 5, label: "پی اچ پی" },
  { id: 15, label: "جاوااسکریپت" },
  { id: 6, label: "دسکتاپ" },
  { id: 17, label: "ری اکت جی اس" },
  { id: 7, label: "سیستم عامل" },
  { id: 8, label: "شبکه" },
  { id: 9, label: "فرانت اند" },
  { id: 10, label: "فلاتر" },
  { id: 11, label: "مهارت های نرم" },
  { id: 20, label: "موبایل و آی او اس" },
  { id: 12, label: "نود جی اس" },
  { id: 13, label: "هوش مصنوعی" },
  { id: 18, label: "وردپرس" },
  { id: 16, label: "ویو جی اس" },
];
export const updateSortOptions = [
  { id: "default", label: "پیشفرض" },
  { id: "popular", label: "پرطرفدار ترین" },
  { id: "newest", label: "جدید ترین" },
  { id: "latest", label: "آخرین آپدیت" },
]
export const courses = [
  {
    id: 1,
    title: "آموزش React از صفر تا ورود به بازار کار",
    href: "/course/react",
    image: "/slider/1.webp",
    description:
      "یادگیری React به صورت پروژه محور و کاملاً کاربردی برای ورود به بازار کار.",
    author: {
      name: "محمدامین سعیدی راد",
      avatar: "/slider/1.webp",
    },
    rating: 4.8,
    students: 300,
    price: 1875000,
    oldPrice: 6250000,
    discount: 70,
  },
  {
    id: 2,
    title: "Next.js حرفه‌ای برای پروژه‌های واقعی",
    href: "/course/nextjs",
    image: "/slider/2.webp",
    description: "ساخت اپلیکیشن‌های SSR و Fullstack با Next.js",
    author: {
      name: "علی رضایی",
      avatar: "/slider/2.webp",
    },
    rating: 4.7,
    students: 300,
    price: 1990000,
    oldPrice: 4000000,
    discount: 50,
  },
  {
    id: 3,
    title: "JavaScript پیشرفته",
    href: "/course/js",
    image: "/slider/3.webp",
    description: "درک عمیق از JS و مفاهیم پیشرفته",
    author: {
      name: "سارا محمدی",
      avatar: "/slider/3.webp",
    },
    rating: 4.6,
    students: 300,
    price: 1500000,
    oldPrice: 3000000,
    discount: 50,
  },
  {
    id: 4,
    title: "TypeScript از صفر تا حرفه‌ای",
    href: "/course/ts",
    image: "/slider/4.webp",
    description: "تایپ‌اسکریپت برای پروژه‌های واقعی",
    author: {
      name: "رضا کریمی",
      avatar: "/slider/4.webp",
    },
    rating: 4.9,
    students: 300,
    price: 2200000,
    oldPrice: 5000000,
    discount: 60,
  },
];